#!/usr/bin/env bash
set -Eeu -o pipefail

# This file is used to run "tmux-test" framework tests.

# "setup" script is needed to run the tests, but it overrides some working dir
# files. To address that, "setup" is run before the tests and its actions are
# undone after.

main() {
	local status=0
	git clone https://github.com/tmux-plugins/tmux-test lib/tmux-test
	lib/tmux-test/setup
	./run_tests || status=$?
	lib/tmux-test/setup 'undo'
	return "$status"
}
main
