#!/usr/bin/env bash

# This file is a symlink from 'tmux-test' plugin.
# You probably don't want to edit it.

# This script should be run within an isolated enviroment (Vagrant, travis).
# Depending on what the tests do, it might NOT be safe to run this script
# directly on the development machine.

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

run_tests() {
	local test_file test_files status=0
	if [[ "$#" -gt 0 ]]; then
		test_files=( "$@" )
	else
		test_files=( "${CURRENT_DIR}/test"* )
	fi
	for test_file in "${test_files[@]}"; do
		echo "Running test: $test_file"
		"${test_file}" || status=$?
	done
	return $status
}

main() {
	run_tests "$@"
}
main "$@"
