#!/usr/bin/env bash

# This file is a symlink from 'tmux-test' plugin.
# You probably don't want to edit it.

# This script should be run within an isolated enviroment (Vagrant, travis).
# Depending on what the tests do, it might NOT be safe to run this script
# directly on the development machine.

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

all_test_files() {
	ls -1 "$CURRENT_DIR" |   # test files are in the current dir
		\grep -i '^test' |   # test file names start with "test"
		xargs                # file names in a single line
}

run_tests() {
	local test_file test_files status=0
	if [[ "$#" -gt 0 ]]; then
		test_files="${@//tests\//}" # remove 'tests/' directory prefix
	else
		test_files="$(all_test_files)"
	fi
	for test_file in $test_files; do
		echo "Running test: $test_file"
		"${CURRENT_DIR}/${test_file}" || status=$?
	done
	return $status
}

main() {
	run_tests "$@"
}
main "$@"
